### ISSUE TITLE
gulp build problems on fresh install

### ISSUE THREAD

**Issue by secretrobotron** [mozilla/webmaker-app#1056]
There are a couple `Cannot find module` messages during `gulp build`. It looks like a couple files are buried in directories, but maybe links to them in code weren't change.
``` bash
[11:04:24] Starting 'browserify-publish'...
[11:04:24]
[11:04:24] Error: Cannot find module '../locale' from '/Users/secretrobotron/src/webmaker-app/publish'
    at /usr/local/lib/node_modules/browserify/node_modules/browser-resolve/node_modules/resolve/lib/async.js:43:25
    at load (/usr/local/lib/node_modules/browserify/node_modules/browser-resolve/node_modules/resolve/lib/async.js:99:43)
    at /usr/local/lib/node_modules/browserify/node_modules/browser-resolve/node_modules/resolve/lib/async.js:105:22
    at /usr/local/lib/node_modules/browserify/node_modules/browser-resolve/node_modules/resolve/lib/async.js:22:47
    at Object.oncomplete (fs.js:107:15)

[11:04:24] Finished 'browserify-publish' after 589 ms
[11:04:24]
[11:04:24] Error: Cannot find module '../locale' from '/Users/secretrobotron/src/webmaker-app/lib'
    at /usr/local/lib/node_modules/browserify/node_modules/browser-resolve/node_modules/resolve/lib/async.js:43:25
    at load (/usr/local/lib/node_modules/browserify/node_modules/browser-resolve/node_modules/resolve/lib/async.js:99:43)
    at /usr/local/lib/node_modules/browserify/node_modules/browser-resolve/node_modules/resolve/lib/async.js:105:22
    at /usr/local/lib/node_modules/browserify/node_modules/browser-resolve/node_modules/resolve/lib/async.js:22:47
    at Object.oncomplete (fs.js:107:15)

[11:04:24] Finished 'browserify' after 663 ms
[11:04:24] Starting 'cache'...
[11:04:25] Finished 'cache' after 229 ms
[11:04:25] Finished 'build' after 3.27 s
```

**Comment by secretrobotron** [comment]
Fixed if I do `npm install graceful-fs` and
``` bash
diff --git a/lib/index.js b/lib/index.js
index c90b953..027341e 100644
--- a/lib/index.js
+++ b/lib/index.js
@@ -9,7 +9,7 @@ require('./shims');
 var Vue = require('vue');

 var i18n = require('./i18n');
-var locale = require('../locale');
+var locale = require('../gulp/locale');
 var router = require('./router');
 var model = require('./model')();
 var Store = require('./storage');
diff --git a/publish/index.js b/publish/index.js
index 14372ad..7a0a3df 100644
--- a/publish/index.js
+++ b/publish/index.js
@@ -6,7 +6,7 @@ var bulk = require('bulk-require');

 // Todo: replace with subset
 var i18n = require('../lib/i18n');
-var locale = require('../locale');
+var locale = require('../gulp/locale');

 var block = require('../lib/block');
 var blocks = clone(bulk(__dirname + '/../blocks', '**/*.js'));
```
